services:
- type: web
  name: aura-backend
  env: node
  region: oregon
  buildCommand: "npm install && npm run build"
  startCommand: "npm start"
  healthCheckPath: "/"
  envVars:
  - key: NODE_VERSION
    value: 22.16.0
  - key: PORT
    value: 5002
  rootDirectory: "backend"
